"""todo

Revision ID: 06dd9fbb4dce
Revises: 
Create Date: 2024-06-28 09:51:32.653864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dd9fbb4dce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_to_do_description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('ix_to_do_task'), ['task'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_to_do_task'))
        batch_op.drop_index(batch_op.f('ix_to_do_description'))

    op.drop_table('to_do')
    # ### end Alembic commands ###
