"""Remove unique constraint from task field

Revision ID: 156bbd9fadf5
Revises: 06dd9fbb4dce
Create Date: 2024-07-09 23:55:04.243255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156bbd9fadf5'
down_revision = '06dd9fbb4dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_index('ix_to_do_description')
        batch_op.create_index(batch_op.f('ix_to_do_description'), ['description'], unique=False)
        batch_op.drop_index('ix_to_do_task')
        batch_op.create_index(batch_op.f('ix_to_do_task'), ['task'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_to_do_task'))
        batch_op.create_index('ix_to_do_task', ['task'], unique=1)
        batch_op.drop_index(batch_op.f('ix_to_do_description'))
        batch_op.create_index('ix_to_do_description', ['description'], unique=1)

    # ### end Alembic commands ###
