"""todo description nullable and not indexed

Revision ID: 3e126caa28f9
Revises: 156bbd9fadf5
Create Date: 2024-07-14 16:33:12.872335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e126caa28f9'
down_revision = '156bbd9fadf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.VARCHAR(length=32), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_to_do_task'), ['task'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_to_do_task'))

    op.drop_table('to_do')
    # ### end Alembic commands ###
