name: Lighthouse CI

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask gunicorn
          pip install -r requirements.txt

      - name: Start Flask application
        run: |
          nohup gunicorn --bind 0.0.0.0:5000 todo:app > /dev/null 2>&1 &
        env:
          FLASK_APP: todo.py
          FLASK_ENV: development

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://example.com/
            https://example.com/blog
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage