name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - run: pip install -r requirements.txt
    - run: coverage run -m unittest discover
    - name: Check coverage
      run: |
        coverage report -m
        coverage report --fail-under=80