name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - run: pip install -r requirements.txt
    - run: coverage run -m unittest discover
    - name: Check coverage
      run: |
        coverage report -m
        coverage report --fail-under=80
    - name: Setup Node.js for Lighthouse
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Lighthouse
      run: npm install -g lighthouse
    - name: Run Lighthouse
      run: lighthouse http://localhost:5000 --output=json --output-path=./lighthouse_report.json