name: CI/CD

on:
  push:
    branches: [main, master]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - run: pip install -r requirements.txt
    - run: python tests.py